package entity

const (
	ORDER_INDEX     = 1
	MILESTONE_INDEX = 2
	WORKORDER_INDEX = 3
	TASK_INDEX      = 4
	WORKLOAD_INDEX  = 5
	STARTDATE_INDEX = 6
	ENDDATE_INDEX   = 7
	EXECUTOR_INDEX  = 8
)

const (
	PLAN_DATE = "01-02-06"
	TASK_DATE = "2006/1/02"
)
